# Generated by Django 3.2.6 on 2022-10-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
